spring:
  datasource:
    pooled: true
    dbCreate: create-drop
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: p4ssw0rd
  # need this due to possible bug with devtools and hibernate 5
  # http://stackoverflow.com/questions/35416308/class-loading-error-with-spring-boot-and-hibernate-5
  devtools:
    restart:
      include:
        all: .*
hibernate:
  hbm2ddl:
    auto: update
#  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory